<?php

use NewEcomAI\ShopSmart\Block\Adminhtml\Widget\DecidePopup;
use Magento\Framework\Escaper;

/** @var DecidePopup $block */
/** @var Escaper $escaper */

$popupPosition = $block->getPopupPosition();
$heading = $block->getHeading();
$placeHolder = $block->getMessagePlaceholder();
$buttonText = $block->getButtonText();
$buttonBackgroundColor = $block->getButtonBackgroundColor();
$sectionBackgroundColor = $block->getSectionBackgroundColor();
$imageRecognition = $block->getImageRecognition();
$layoutText = $block->getLayoutText();
$layoutDescriptionText = $block->getLayoutDescriptionText();
$exampleQueryOne = $block->getExampleQueryOne();
$exampleQueryTwo = $block->getExampleQueryTwo();
$exampleQueryThree = $block->getExampleQueryThree();
$exampleQueryFour = $block->getExampleQueryFour();
$exampleQueryFive = $block->getExampleQueryFive();
$destinationStatus = $block->getDestinaltionStatus();
$customCss = $block->getCustomCss();
$configHelper = $block->getConfigHelper();
$showProductGrid = $block->getProductGrid();
$currentProduct = $block->getCurrentProduct();
$currentProductDetail = preg_replace('/\s+/', ' ', html_entity_decode(strip_tags($currentProduct->getDescription())));
$popupImage = $block->getImageUrl();
$productRecommendation = $block->getProductRecommendation();
if ($configHelper->isDecideWidgetEnabled() && $popupPosition):?>
    <?= $customCss ? $escaper->escapeCss($customCss) : ""; ?>
    <div class="decide_widget" style="display: none">
        <div class="NewEcomAi newSmartShopDecide <?= $escaper->escapeHtml($popupPosition); ?>">
            <div id="newcom-popup" class="popup NewEcomAi__popup">
                <div class="popup-content NewEcomAi__popup-content js-newcom-popup-content"
                     style="background-color: <?= $escaper->escapeHtml($sectionBackgroundColor); ?>">
                    <?php if ($popupImage): ?>
                        <div class="NewEcomAi__popup-content__column image">
                            <div class="NewEcomAi__popup-content__image-container">
                                <img class="NewEcomAi__popup-content__image-container__img"
                                     src="<?= $escaper->escapeHtml($popupImage); ?>"
                                     alt="Popup Image"/>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="NewEcomAi__popup-content__column content">
                        <span class="close NewEcomAi__close" id="newComclose">&times;</span>
                        <div class="NewEcomAi__popup-content__inner">
                            <h2 class="NewEcomAi__popup-content__heading">
                                <?= $heading ? $escaper->escapeHtml($heading) :
                                    $escaper->escapeHtml(__('Ask me anything you want
                                    about this product in Natural Language.')); ?>
                            </h2>
                            <div class="NewEcomAi__popup-content__search-box">
                                <input class="NewEcomAi__popup-content__input" rows="2" name="NewEcomAi-question"
                                       id="NewEcomAi-question" alt=""
                                       placeholder="<?= $placeHolder ? $escaper->escapeHtml($placeHolder) :
                                           $escaper->escapeHtml(__('Can I wear this product for a formal diner?')); ?>">
                                <button id="NewEcomAi-search" class="NewEcomAi__popup-content__button"
                                        style="background-color: <?= $escaper->escapeHtml($buttonBackgroundColor);?>">
                                    <?= $buttonText ? $escaper->escapeHtml($buttonText) :
                                        $escaper->escapeHtml(__('Tell me'));?>
                                </button>
                            </div>

                            <div class="NewEcomAi__popup-content__examples">
                                <div class="NewEcomAi__popup-content__examples__query newcomClickableText">
                                    <span class="NewEcomAi__popup-content__examples__query__text">
                                        <?= $exampleQueryOne ? $escaper->escapeHtml($exampleQueryOne) :
                                            $escaper->escapeHtml(__("What are the materials?")); ?>
                                    </span>
                                </div>
                                <?php if ($exampleQueryTwo): ?>
                                    <div class="NewEcomAi__popup-content__examples__query newcomClickableText">
                                        <span class="NewEcomAi__popup-content__examples__query__text">
                                            <?= $escaper->escapeHtml($exampleQueryTwo); ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                                <?php if ($exampleQueryThree): ?>
                                    <div class="NewEcomAi__popup-content__examples__query newcomClickableText">
                                        <span class="NewEcomAi__popup-content__examples__query__text">
                                            <?= $escaper->escapeHtml($exampleQueryThree); ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                                <?php if ($exampleQueryFour): ?>
                                    <div class="NewEcomAi__popup-content__examples__query newcomClickableText">
                                        <span class="NewEcomAi__popup-content__examples__query__text">
                                            <?= $escaper->escapeHtml($exampleQueryFour); ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                                <?php if ($exampleQueryFive): ?>
                                    <div class="NewEcomAi__popup-content__examples__query newcomClickableText">
                                        <span class="NewEcomAi__popup-content__examples__query__text">
                                            <?= $escaper->escapeHtml($exampleQueryFive); ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <div id="NewEcomAi-search-result" class="NewEcomAi__popup-content__response"></div>
                </div>
            </div>
            <div class="NewEcomAi__right NewEcomAi__btn" id="newcomRightBtn">
                <div class="NewEcomAi__right__text">
                    <?= $layoutText ? $escaper->escapeHtml($layoutText) :
                        $escaper->escapeHtml(__('Shop Smart')); ?>
                </div>
                <div class="NewEcomAi__right__desc">
                    <?= $layoutDescriptionText ? $escaper->escapeHtml($layoutDescriptionText) :
                        $escaper->escapeHtml(__('AI Powered Shopping Assistant')); ?>
                </div>
            </div>
            <div class="NewEcomAi__left NewEcomAi__btn" id="newcomLeftBtn">
                <div class="NewEcomAi__left__desc">
                    <?= $layoutDescriptionText ? $escaper->escapeHtml($layoutDescriptionText) :
                        $escaper->escapeHtml(__('AI Powered Shopping Assistant')); ?>
                </div>
                <div class="NewEcomAi__left__text">
                    <?= $layoutText ? $escaper->escapeHtml($layoutText) :
                        $escaper->escapeHtml(__('Shop Smart')); ?>
                </div>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "decideSearchNewEcom": {
                    "decideSearchUrl": "<?= $escaper->escapeUrl($block->getDecideSearchUrl());?>",
                    "decideSearchQuestionRateUrl": "<?= $escaper->escapeUrl($block->getDecideSearchQuestionRateUrl());?>",
                    "productGridLayout": "<?= $escaper->escapeHtml($showProductGrid);?>",
                    "currentProductTitle": "<?= $escaper->escapeHtml($currentProduct->getName());?>",
                    "currentProductDescription": "<?= $escaper->escapeHtml(preg_replace('/\s+/', ' ', html_entity_decode(strip_tags($currentProduct->getDescription()))));?>",
                    "productRecommendation": "<?= $escaper->escapeHtml($productRecommendation);?>",
                    "currentProductId": "<?= $escaper->escapeHtml($currentProduct->getId());?>",
                    "productAddToCartUrl": "<?= $escaper->escapeUrl($block->productAddToCartUrl());?>"
                }
            }
        }
    </script>
    <script>
        require(['jquery', 'customNewcom'], function ($, customNewcom) {
            customNewcom();
        });
    </script>
<?php endif; ?>
