<?php

use NewEcomAi\ShopSmart\Block\System\Config\Button\CatalogSyncExecution;
use Magento\Framework\Escaper;

/** @var CatalogSyncExecution $block */
/** @var Escaper $escaper */

$dataHelper = $block->getHelper();

?>
<div class="pp-buttons-container" id="catalog_sync">
    <button id="catalog_sync_button">
        <span><span><span><?= $escaper->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
    <br><br>
    <span id="lastSynced" ><?= $escaper->escapeHtml(__('Catalog last synced at : ')); ?>
        <span class='dateTime'>
            <strong>
                <?= $escaper->escapeHtml($dataHelper->getShopSmartCatalogSyncDate());?>
            </strong>
        </span>
    </span>
    <div id="overlay" class="success_msg" style="display: none">
        <div id="popup">
            <header class="modal-header">
                <h1 id="modal-title-0" class="modal-title" data-role="title">
                    <?= $escaper->escapeHtml(__('Success!')); ?></h1>
                <button class="action-close" data-role="closeBtn" type="button">
                    <span><?= $escaper->escapeHtml(__('Close')); ?></span>
                </button>
            </header>
            <div id="modal-content-0" class="modal-content" data-role="content">
                <div class="popup-modal" style="">
                    <p><?= $escaper->escapeHtml(__('Catalog Sync Run Successfully.')); ?></p>
                    <div class="modal_close_btn">
                        <button class="close_popup"><?= $escaper->escapeHtml(__('Ok')); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="overlay" class="error_msg" style="display: none">
        <div id="popup">
            <header class="modal-header">
                <h1 id="modal-title-0" class="modal-title" data-role="title"><?= $escaper->escapeHtml(__('Error!')); ?></h1>
                <button class="action-close" data-role="closeBtn" type="button">
                    <span><?= $escaper->escapeHtml(__('Close')); ?></span>
                </button>
            </header>
            <div id="modal-content-0" class="modal-content" data-role="content">
                <div class="popup-modal" style="">
                    <p> <?= $escaper->escapeHtml(__('Catalog Sync Failed.')); ?> </p>
                    <p class="custom_error"></p>
                    <div class="modal_close_btn">
                        <button class="close_popup"><?= $escaper->escapeHtml(__('Ok')); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    (function () {
        require(["jquery"], function ($) {
            $(document).ready(function ($) {
                $("#catalog_sync_button").on("click", function (e) {
                    e.preventDefault();
                    $('.custom_error').text('');
                    $('.dateTime').html('');
                    $('#catalog_sync #lastSynced').hide();
                    $.ajax({
                        url: "<?= $escaper->escapeUrl($block->getUrl('newecomai/config/catalogproductsync')); ?>",
                        data: {form_key: window.FORM_KEY,buttonClicked:"1"},
                        showLoader: true,
                        type: "POST",
                        success: function (response, status) {
                            if (response.status) {
                                let lastSyncDate = response.lastSyncDate;
                                $('#catalog_sync .success_msg').show();
                                $('#catalog_sync #lastSynced').show();
                                $("#catalog_sync #lastSynced").append("<span class='dateTime'><strong>"+lastSyncDate+'</strong></span>');

                            } else {
                                $('#catalog_sync .custom_error').text(response.message)
                                $('#catalog_sync .error_msg').show();
                            }
                        },
                        error: function (error, status) {
                            $('#catalog_sync .error_msg').show();

                        }
                    })
                })
                $('#catalog_sync .modal-header .action-close, .modal_close_btn').click(function (e) {
                    $('#catalog_sync .success_msg').hide();
                    $('#catalog_sync .error_msg').hide();
                    e.preventDefault()
                });
            });
        });
    })();
</script>

